[project]
name = "pixi-docker-example"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "linux-aarch64", "win-64"]

[tasks]
dev = "uvicorn my_project:app --reload"
start = "uvicorn my_project:app"

[dependencies]
fastapi = "*"
uvicorn = "*"
pytest = "*"
ruff = "*"
mypy = "*"
